#!/usr/bin/env python3
"""Derive sorter metrics from theory and experiment matrices."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

from _tau_metric_common import (
    default_final_data_dir,
    default_output_dir,
    default_theory_csv,
    eta_sort,
    mutual_information_bits,
    normalize_columns,
    per_channel_metrics,
    read_er_summary_sheet,
    read_matrix_sheet,
    read_theory_matrix_csv,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compute eta_sort, e_sort and mutual information.")
    parser.add_argument(
        "--theory-csv",
        type=Path,
        default=default_theory_csv(),
        help="Theory matrix CSV generated by 01_tau_kernel_to_probability_matrix.py.",
    )
    parser.add_argument(
        "--final-data-dir",
        type=Path,
        default=default_final_data_dir(),
        help="Directory containing triplicate_full9_aggregate.xlsx and run folders 1/2/3.",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Directory for generated outputs. Defaults to the script directory.",
    )
    return parser.parse_args()


def write_metrics_csv(path: Path, dataset_name: str, metrics_rows, eta_value: float, info_bits: float) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            ["dataset", "channel_l", "diag_share_pct", "e_sort_pct", "ER_sum_db_from_matrix", "ER_max_db_from_matrix"]
        )
        for row in metrics_rows:
            writer.writerow(
                [
                    dataset_name,
                    int(row["l"]),
                    f"{100.0 * row['diag_share']:.6f}",
                    f"{100.0 * row['e_sort']:.6f}",
                    f"{row['er_sum_db']:.6f}",
                    f"{row['er_max_db']:.6f}",
                ]
            )
        writer.writerow([dataset_name, "ALL", f"{100.0 * eta_value:.6f}", f"{100.0 * (1.0 - eta_value):.6f}", "", ""])
        writer.writerow([dataset_name, "mutual_information_bits", f"{info_bits:.6f}", "", "", ""])


def main() -> None:
    args = parse_args()
    out_dir = default_output_dir(args.output_dir)

    theory = read_theory_matrix_csv(args.theory_csv)
    theory_metrics = per_channel_metrics(theory)
    theory_eta = eta_sort(theory)
    theory_info = mutual_information_bits(theory)

    aggregate_xlsx = args.final_data_dir / "triplicate_full9_aggregate.xlsx"
    experiment = normalize_columns(read_matrix_sheet(aggregate_xlsx, "combined_percentage"), scale=1.0)
    experiment_metrics = per_channel_metrics(experiment)
    experiment_eta = eta_sort(experiment)
    experiment_info = mutual_information_bits(experiment)
    er_summary = read_er_summary_sheet(aggregate_xlsx)

    theory_csv = out_dir / "theory_metrics.csv"
    experiment_csv = out_dir / "experiment_metrics.csv"
    write_metrics_csv(theory_csv, "theory", theory_metrics, theory_eta, theory_info)
    write_metrics_csv(experiment_csv, "experiment_aggregate", experiment_metrics, experiment_eta, experiment_info)

    metrics_txt = out_dir / "metrics_comparison.txt"
    with metrics_txt.open("w", encoding="utf-8") as handle:
        handle.write("Theory and experiment sorter metrics\n\n")
        handle.write(f"theory_csv = {args.theory_csv}\n")
        handle.write(f"aggregate_xlsx = {aggregate_xlsx}\n")
        handle.write("aggregate_sheet = combined_percentage\n")
        handle.write("ER_summary_sheet = ER_summary\n\n")
        handle.write(
            f"theory: eta_sort={100.0 * theory_eta:.6f}%, "
            f"e_sort={100.0 * (1.0 - theory_eta):.6f}%, "
            f"I={theory_info:.6f} bits\n"
        )
        handle.write(
            f"experiment: eta_sort={100.0 * experiment_eta:.6f}%, "
            f"e_sort={100.0 * (1.0 - experiment_eta):.6f}%, "
            f"I={experiment_info:.6f} bits\n\n"
        )
        handle.write("Per-channel consistency with ER_summary:\n")
        max_er_sum_diff = 0.0
        max_er_max_diff = 0.0
        for row in experiment_metrics:
            label = int(row["l"])
            ref = er_summary[label]
            er_sum_diff = abs(row["er_sum_db"] - ref["er_sum_mean_db"])
            er_max_diff = abs(row["er_max_db"] - ref["er_max_mean_db"])
            max_er_sum_diff = max(max_er_sum_diff, er_sum_diff)
            max_er_max_diff = max(max_er_max_diff, er_max_diff)
            handle.write(
                "  "
                f"l={label}: ER_sum_from_matrix={row['er_sum_db']:.6f} dB vs ER_summary={ref['er_sum_mean_db']:.6f} dB; "
                f"ER_max_from_matrix={row['er_max_db']:.6f} dB vs ER_summary={ref['er_max_mean_db']:.6f} dB\n"
            )
        handle.write("\n")
        handle.write(f"max_abs_diff_ER_sum_db = {max_er_sum_diff:.6f}\n")
        handle.write(f"max_abs_diff_ER_max_db = {max_er_max_diff:.6f}\n")
        handle.write(
            "\n"
            "Note: ER_sum is recomputed from the aggregated percentage matrix and should stay very close to\n"
            "the ER_summary sheet. ER_max can differ more because max() is nonlinear: averaging the per-run\n"
            "ER_max values is not the same operation as taking the maximum crosstalk channel after averaging\n"
            "the matrix itself.\n"
        )

    print(f"Wrote {theory_csv}")
    print(f"Wrote {experiment_csv}")
    print(f"Wrote {metrics_txt}")
    print(
        "Aggregate metrics: "
        f"eta_sort={100.0 * experiment_eta:.3f}%, "
        f"e_sort={100.0 * (1.0 - experiment_eta):.3f}%, "
        f"I={experiment_info:.4f} bits"
    )


if __name__ == "__main__":
    main()
